import cv from "../assets/staff/foto_cv.jpg";
import cv2 from "../assets/staff/foto_cv2.jpg";

export const ourStaff = [
    { id: 1,
    name: 'Eduardo J. Marteleur',
    image: cv2,
    position: 'Presidente',
    email: 'eduardomarteleur@msf.com.ar',
    tel: '+54 9 3564-652100'},
    { id: 2,
    name: 'Eduardo J. Marteleur',
    image: cv2,
    position: 'Presidente',
    email: 'eduardomarteleur@msf.com.ar',
    tel: '+54 9 3564-652100'},
    { id: 3,
    name: 'Eduardo J. Marteleur',
    image: cv2,
    position: 'Presidente',
    email: 'eduardomarteleur@msf.com.ar',
    tel: '+54 9 3564-652100'},
    { id: 4,
    name: 'Eduardo J. Marteleur',
    image: cv2,
    position: 'Presidente',
    email: 'eduardomarteleur@msf.com.ar',
    tel: '+54 9 3564-652100'},
    { id: 5,
    name: 'Eduardo J. Marteleur',
    image: cv2,
    position: 'Presidente',
    email: 'eduardomarteleur@msf.com.ar',
    tel: '+54 9 3564-652100'},
    { id: 6,
    name: 'Eduardo J. Marteleur',
    image: cv2,
    position: 'Presidente',
    email: 'eduardomarteleur@msf.com.ar',
    tel: '+54 9 3564-652100'},
    
]